# Generated by Django 5.2 on 2025-05-01 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureInModel',
            fields=[
                ('feature_in_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_control.feature')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_control.model')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterInModel',
            fields=[
                ('parameter_in_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_control.model')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_control.parameter')),
            ],
        ),
    ]
