# Generated by Django 5.2 on 2025-05-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0002_featureinmodel_parameterinmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureinmodel',
            name='value',
        ),
    ]
