# Generated by Django 5.2 on 2025-05-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0003_remove_featureinmodel_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='description',
            field=models.CharField(default=''),
        ),
    ]
