# Generated by Django 5.2 on 2025-05-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0004_parameter_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='description',
            field=models.CharField(),
        ),
    ]
