# Generated by Django 5.2 on 2025-05-05 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0005_alter_parameter_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureinmodel',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_control.feature'),
        ),
        migrations.AlterField(
            model_name='featureinmodel',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_control.model'),
        ),
        migrations.AlterField(
            model_name='parameterinmodel',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_control.model'),
        ),
        migrations.AlterField(
            model_name='parameterinmodel',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_control.parameter'),
        ),
    ]
