# Generated by Django 5.2 on 2025-05-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0006_alter_featureinmodel_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='param_type',
            field=models.CharField(choices=[('int', 'Integer'), ('float', 'Float')], default='float', max_length=10),
        ),
    ]
