# Generated by Django 5.2 on 2025-05-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0007_parameter_param_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='param_type',
            field=models.CharField(choices=[('int', 'Integer'), ('float', 'Float')], max_length=10),
        ),
    ]
